## numpy是一个多维数组对象

In [1]:
import numpy as np
data=[1,2,3,4,5]
n=np.array(data*10)
print(data)
print(n)

[1, 2, 3, 4, 5]
[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2
 3 4 5 1 2 3 4 5 1 2 3 4 5]


## 基本方法

In [2]:
n.shape

(50,)

In [3]:
n.dtype

dtype('int32')

# 嵌套序列，是由一组等长列表组成的列表

In [4]:
arr=[
    [1,2,3,4],
    [1,2,3,4]
]
arr2=np.array(arr)
print(arr2)
print(arr2.ndim)#维度
print(arr2.shape)#大小

[[1 2 3 4]
 [1 2 3 4]]
2
(2, 4)


# np对字符串的判断

In [5]:
arr=[
    ['1','2',3,'4'],
    [3,4,5,6]
]
arr2=np.array(arr)
print(arr2)
print(arr2.dtype)

[['1' '2' '3' '4']
 ['3' '4' '5' '6']]
<U1


In [6]:
arr=[
    [1,2,3,4],
    [3,4,5,6]
]
arr2=np.array(arr)
print(arr2)
print(arr2.dtype)

[[1 2 3 4]
 [3 4 5 6]]
int32


In [7]:
arr=[
    [1.1,2,3,4],
    [3,4,5,6]
]
arr2=np.array(arr)
print(arr2)
print(arr2.dtype)#元素中有一个float时全变

[[1.1 2.  3.  4. ]
 [3.  4.  5.  6. ]]
float64


# np指定长度数组创建 

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr=np.array([1.2,1.6])
print(arr)
print(arr.dtype)
print(arr.astype('int'))

[1.2 1.6]
float64
[1 1]


## 矢量化
数组不用在编写循环的情况下进行批量运算

In [12]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr1+arr2

array([ 6,  8, 10, 12])

In [13]:
arr2*5

array([25, 30, 35, 40])

# numpy数组索引切片操作

In [14]:
arr=np.arange(10)
print(arr)
print(arr[:3])
print(arr[2])
arr[0:4]=12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
2
[12 12 12 12  4  5  6  7  8  9]


# numpy数组转置和轴对换

In [15]:
arr=np.arange(24).reshape(2,3,4)
print(arr)
print('*'*10)
print(arr.T)
print('*'*10)
print(arr.transpose(2,1,0))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
**********
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
**********
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


# 条件逻辑转数组
np.where等同于x if condition else y
用于一个数组产生一个新的数组

In [16]:
x_arr=np.array([1.1,1.2,1.3])
y_arr=np.array([2.1,2.2,2.3])
condition=np.array([True,False,True])
re=[(x if c else y) for x,y,c in zip(x_arr,y_arr,condition)]
print(re)

[1.1, 2.2, 1.3]


In [17]:
r=np.where(condition,x_arr,y_arr)
print(r)

[1.1 2.2 1.3]


In [18]:
#值替换
arr=np.random.randn(4,4)
print(arr)
print(np.where(arr>0,1,-1))

[[ 0.51239315 -0.08431073  1.5980928  -0.00271176]
 [-0.39726617  0.50111272  0.69836467 -0.3292938 ]
 [ 1.47231288 -0.15055223  0.24706411 -1.6005081 ]
 [-1.91549496 -1.07550069  0.69607031 -1.304885  ]]
[[ 1 -1  1 -1]
 [-1  1  1 -1]
 [ 1 -1  1 -1]
 [-1 -1  1 -1]]


In [19]:
arr=np.random.randn(4)
print(arr)
arr.sort()
print(arr)

[-1.11949432  1.04426576 -0.84461597  0.02619638]
[-1.11949432 -0.84461597  0.02619638  1.04426576]


In [20]:
arr=np.random.randn(4,4)
print(arr)
arr.sort(1)
print(arr)

[[ 0.12252768  0.11606375  0.61839802  0.64569743]
 [ 1.77357524 -0.81663513 -0.59431161 -1.99238029]
 [ 2.01428104  0.98407933  1.41339811 -1.27648981]
 [ 0.88588886  1.21878355 -1.33895525  0.19638574]]
[[ 0.11606375  0.12252768  0.61839802  0.64569743]
 [-1.99238029 -0.81663513 -0.59431161  1.77357524]
 [-1.27648981  0.98407933  1.41339811  2.01428104]
 [-1.33895525  0.19638574  0.88588886  1.21878355]]


# numpy的文件操作
numpy可以读写磁盘上的文件或者是二进制数据

In [21]:
arr=np.arange(10)
print(arr)
np.save('demo',arr)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
print(np.load('demo.npy'))

[0 1 2 3 4 5 6 7 8 9]


In [23]:
arr=np.arange(9)
np.savez('demoz',a=arr)

In [24]:
print(np.load('demoz.npz')['a'])

[0 1 2 3 4 5 6 7 8]


In [25]:
arr=np.arange(9)
np.savetxt('demo.txt',arr,delimiter=',')#分隔符

In [26]:
print(np.loadtxt('demo.txt',delimiter=','))

[0. 1. 2. 3. 4. 5. 6. 7. 8.]


# 线性代数
dot 矩阵的乘法运算
trace 计算对角元素的和
det 计算矩阵的行列式
eig 计算方阵特征值和特征向量

In [27]:
x=np.array([[1,2],[3,4]])
print(x.dot(x))

[[ 7 10]
 [15 22]]


## 随机漫步

In [28]:
import matplotlib.pyplot as plt
position=0#初始值
walk=[position]#步值初始化
stops=1000#步数设置
for i in range(stops):
    step=1 if np.random.randint(0,2) else -1
    position+=step
    walk.append(position)
plt.plot(walk) 
plt.show()

<Figure size 640x480 with 1 Axes>

# pandas

In [29]:
import pandas as pd
from pandas import Series,DataFrame

## Series类型说明
类似于一维数组对象，带有索引

In [30]:
obj=Series([1,2,3,4,5])
print(obj)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [31]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [32]:
obj.values

array([1, 2, 3, 4, 5], dtype=int64)

In [33]:
#自定义索引
obj=Series([1,2,3],index=['a','b','c'])
print(obj)

a    1
b    2
c    3
dtype: int64


In [34]:
#Serices 当作字典使用
dit={'a':10,'b':100}
obj=Series(dit)
keys=['a']
obj_1=Series(dit,index=keys)
print(obj)
print(obj_1)

a     10
b    100
dtype: int64
a    10
dtype: int64


In [35]:
#缺失数据处理
datas={'a':None,'b':100,'c':200}
obj=Series(datas)
print(obj)

a      NaN
b    100.0
c    200.0
dtype: float64


In [36]:
pd.isnull(obj)

a     True
b    False
c    False
dtype: bool

## Dataframe

In [38]:
#构建dataframe
data={
    'a':[1,2,3],
    'b':[4,5,6],
    'c':[7,8,9]
}
frame=DataFrame(data)
print(frame)
print(frame['a'])

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9
0    1
1    2
2    3
Name: a, dtype: int64


In [39]:
import numpy as np

dates=pd.date_range('20190301',periods=6)
print(dates)

DatetimeIndex(['2019-03-01', '2019-03-02', '2019-03-03', '2019-03-04',
               '2019-03-05', '2019-03-06'],
              dtype='datetime64[ns]', freq='D')


In [40]:
df=DataFrame(np.random.rand(6,4),index=dates,columns=list('abcd'))
print(df)

                   a         b         c         d
2019-03-01  0.218225  0.904628  0.143368  0.238122
2019-03-02  0.201575  0.202822  0.688100  0.291832
2019-03-03  0.764097  0.302175  0.233053  0.727010
2019-03-04  0.439688  0.916934  0.493296  0.941007
2019-03-05  0.071678  0.967715  0.640015  0.745885
2019-03-06  0.527956  0.438550  0.794397  0.927092


In [41]:
df.T

2019-03-01  2019-03-02  2019-03-03  2019-03-04  2019-03-05  2019-03-06
a    0.218225    0.201575    0.764097    0.439688    0.071678    0.527956
b    0.904628    0.202822    0.302175    0.916934    0.967715    0.438550
c    0.143368    0.688100    0.233053    0.493296    0.640015    0.794397
d    0.238122    0.291832    0.727010    0.941007    0.745885    0.927092

In [42]:
df['20190301':'20190303']

a         b         c         d
2019-03-01  0.218225  0.904628  0.143368  0.238122
2019-03-02  0.201575  0.202822  0.688100  0.291832
2019-03-03  0.764097  0.302175  0.233053  0.727010

In [43]:
df.loc['20190301','a']

0.21822516806698578

### Dataframe可以接收哪些类型
二维数组
数组组成的字典
字典组成的字典
字典或Serices的列表

## pandas重新索引reindex

In [44]:
obj=Series([4.5,9.8,-1.2],index=['a','b','c'])
print(obj)

a    4.5
b    9.8
c   -1.2
dtype: float64


In [46]:
obj_1=obj.reindex(['a','b','c','d','e','f'])
print(obj_1)

a    4.5
b    9.8
c   -1.2
d    NaN
e    NaN
f    NaN
dtype: float64


In [47]:
obj.reindex(['a','b','c','d','e','f'],fill_value=1)

a    4.5
b    9.8
c   -1.2
d    1.0
e    1.0
f    1.0
dtype: float64

In [48]:
obj=Series([4.5,9.8,-1.2],index=[0,2,4])
o=obj.reindex(range(6),method='ffill')
print(obj)
print(o)

0    4.5
2    9.8
4   -1.2
dtype: float64
0    4.5
1    4.5
2    9.8
3    9.8
4   -1.2
5   -1.2
dtype: float64


## 算术运算和数组对齐

In [49]:
d1=Series([1.3,1.5,2.6,-3.5],index=['a','b','c','d'])
d2=Series([2.3,-3.5,5.6,-6.5,10],index=['a','b','c','d','e'])
d1+d2

a     3.6
b    -2.0
c     8.2
d   -10.0
e     NaN
dtype: float64

In [50]:
df1=DataFrame(np.arange(9).reshape((3,3)),columns=list('abc'),index=[1,2,3])
print(df1)

   a  b  c
1  0  1  2
2  3  4  5
3  6  7  8


In [51]:
df2=DataFrame(np.arange(12).reshape((4,3)),columns=list('cde'),index=[1,2,3,4])
print(df2)

   c   d   e
1  0   1   2
2  3   4   5
3  6   7   8
4  9  10  11


In [52]:
df1+df2

a   b     c   d   e
1 NaN NaN   2.0 NaN NaN
2 NaN NaN   8.0 NaN NaN
3 NaN NaN  14.0 NaN NaN
4 NaN NaN   NaN NaN NaN

In [55]:
df1.add(df2,fill_value=10)

a     b     c     d     e
1  10.0  11.0   2.0  11.0  12.0
2  13.0  14.0   8.0  14.0  15.0
3  16.0  17.0  14.0  17.0  18.0
4   NaN   NaN  19.0  20.0  21.0

## 排序

In [57]:
obj=Series(range(5),index=['d','e','c','a','b'])
print(obj)

d    0
e    1
c    2
a    3
b    4
dtype: int64


In [58]:
obj.sort_index()

a    3
b    4
c    2
d    0
e    1
dtype: int64

In [59]:
obj.sort_values()

d    0
e    1
c    2
a    3
b    4
dtype: int64

In [60]:
#根据任意一个轴上的索引排序
frame=DataFrame(np.arange(8).reshape((2,4)),index=['two','one'],columns=['c','d','b','a'])

In [61]:
frame

c  d  b  a
two  0  1  2  3
one  4  5  6  7

In [62]:
frame.sort_index()

c  d  b  a
one  4  5  6  7
two  0  1  2  3

In [63]:
frame.sort_index(axis=1)

a  b  c  d
two  3  2  0  1
one  7  6  4  5

## 层次化索引

In [67]:
data=Series(np.arange(10),index=[
    ['a','a','a','b','b','b','c','c','c','d'],
    [1,2,3,4,5,6,1,2,3,4]
])
data

a  1    0
   2    1
   3    2
b  4    3
   5    4
   6    5
c  1    6
   2    7
   3    8
d  4    9
dtype: int32

In [68]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3, 4, 5, 6]],
           codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2, 3], [0, 1, 2, 3, 4, 5, 0, 1, 2, 3]])

In [69]:
data['b']

4    3
5    4
6    5
dtype: int32

In [70]:
data[:2]

a  1    0
   2    1
dtype: int32